name: Export Android APK

on:
  push:
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Export Android debug APK
        run: |
          mkdir -v -p build/android
          godot --headless --verbose --export-debug "Android" build/android/PlatformWonderDemo.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android
